name: Vercel Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run type-check
        if: hashFiles('tsconfig.json') != ''

      - name: Unit Tests
        run: npm test

  deploy-preview:
    name: Deploy Preview
    needs: quality-checks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT

      - name: Assign Custom Alias
        id: alias
        run: |
          branch="${{ github.head_ref }}"
          safe_branch=$(echo "$branch" | tr '/' '-' | tr '_' '-' | tr '[:upper:]' '[:lower:]')
          alias="pr-${{ github.event.pull_request.number }}-preview.vercel.app"
          vercel alias set ${{ steps.deploy.outputs.url }} $alias --token=${{ secrets.VERCEL_TOKEN }} || true
          echo "alias=$alias" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `🚀 **Preview Deployment Ready**

            📱 **Preview URL:** ${{ steps.deploy.outputs.url }}
            ${process.env.ALIAS ? `🔗 **Custom Alias:** https://${process.env.ALIAS}` : ''}

            **Commit:** ${context.sha.substring(0, 7)}
            **Branch:** ${{ github.head_ref }}

            <details>
            <summary>Deployment Details</summary>

            - **Environment:** Preview
            - **Workflow Run:** [View Logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
        env:
          ALIAS: ${{ steps.alias.outputs.alias }}

  deploy-production:
    name: Deploy Production
    needs: quality-checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.promote.outputs.url }}
    outputs:
      production-url: ${{ steps.promote.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Staging
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --prod --skip-domain --token=${{ secrets.VERCEL_TOKEN }})
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "Deployed to staging: $url"

      - name: Wait for Deployment
        run: sleep 30

      - name: Health Check
        id: health
        run: |
          max_retries=30
          retry_delay=10
          retries=0
          
          while [ $retries -lt $max_retries ]; do
            http_code=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.deploy.outputs.url }}/api/health" || echo "000")
            
            if [ "$http_code" == "200" ]; then
              echo "✅ Health check passed"
              exit 0
            fi
            
            retries=$((retries + 1))
            echo "Attempt $retries/$max_retries: HTTP $http_code, retrying in ${retry_delay}s..."
            sleep $retry_delay
          done
          
          echo "❌ Health check failed"
          exit 1

      - name: Promote to Production
        id: promote
        if: success()
        run: |
          vercel promote ${{ steps.deploy.outputs.url }} --token=${{ secrets.VERCEL_TOKEN }}
          echo "url=${{ steps.deploy.outputs.url }}" >> $GITHUB_OUTPUT
          echo "✅ Promoted to production"

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "❌ Deployment failed, removing staging deployment"
          vercel remove ${{ steps.deploy.outputs.url }} --yes --token=${{ secrets.VERCEL_TOKEN }}

  e2e-tests:
    name: E2E Tests
    needs: deploy-production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run E2E Tests
        env:
          TEST_URL: ${{ needs.deploy-production.outputs.production-url }}
        run: npm run test:e2e
        if: hashFiles('playwright.config.ts') != '' || hashFiles('cypress.config.ts') != ''

  notify:
    name: Notify
    needs: [deploy-production, e2e-tests]
    if: always() && (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        if: needs.deploy-production.result == 'success' && needs.e2e-tests.result == 'success'
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "✅ Production deployment succeeded",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production Deployment Complete* ✅\n\n*URL:* ${{ needs.deploy-production.outputs.production-url }}\n*Commit:* ${{ github.sha }}\n*Actor:* ${{ github.actor }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Failure
        if: needs.deploy-production.result == 'failure' || needs.e2e-tests.result == 'failure'
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "❌ Production deployment failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Production Deployment Failed* ❌\n\n*Commit:* ${{ github.sha }}\n*Actor:* ${{ github.actor }}\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  cleanup-preview:
    name: Cleanup Preview
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Remove Preview Deployments
        run: |
          deployments=$(vercel list --meta pr=${{ github.event.pull_request.number }} --token=${{ secrets.VERCEL_TOKEN }} | jq -r '.deployments[].url' || echo "")
          
          for deployment in $deployments; do
            echo "Removing $deployment"
            vercel remove $deployment --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          done
